### ISSUE TITLE
wykop api

### ISSUE THREAD

**Issue by wklm** [sdadas/taggraph#1]
Hej, 

czy wykop udostepnia streaming api (na websokcets) jak twitter?

pzdr,
Wojtek

**Comment by sdadas** [comment]
Cześć,
Nie wydaje mi się, publiczne API wykopu wymaga cyklicznego odpytywania o nowe wpisy. Osobiście nie korzystałem z API, dane do tego projektu maja dosyć prostą strukturę więc scrawlowałem je bezpośrednio ze strony wykopu. 

Pozdrawiam
